server:
  servlet:
    context-path: /ml
  port: 8088

spring:
#  main:
#    web-application-type: none
  application:
    name: spring-boot-multilingual
  h2:
    console:
      enabled=true:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  jpa:
    hibernate.ddl-auto: create
    generate-ddl: true
    show-sql: true

logging:
  org.springframework.web: INFO
  org.rdas: DEBUG





